import Head from "next/head";
import {
  Badge,
  Box,
  Button,
  Divider,
  Flex,
  Grid,
  GridItem,
  HStack,
  Heading,
  IconButton,
  SimpleGrid,
  Stack,
  Text,
} from "@chakra-ui/react";
import {
  FaLinkedinIn,
  FaInstagram,
  FaYoutube,
  FaSpotify,
} from "react-icons/fa6";
import onboarding from "@assets/onboarding.svg";
import diagnosis from "@assets/diagnosis.svg";
import logo from "@assets/logo.png";
import googlePartner from "@assets/google_partner.png";
import metaBusiness from "@assets/meta_business.png";
import metaCertified from "@assets/meta_certified.png";
import learning from "@assets/learning.svg";
import growth_cicle from "@assets/growth_cicle.svg";
import ex from "@assets/ex.png";
import exDois from "@assets/ex_dois.png";
import H1 from "@/components/H1";
import Paragraph from "@/components/Paragraph";
import Header from "@/components/Header";
import Image from "next/image";
import { COMPANIES, PARTNERS } from "@/constants";
import ills from "@assets/illustration.svg";
import funil from "@assets/funil.png";
import Texture from "@/components/Texture";
import puzzle from "@assets/puzzle.svg"
import chart from "@assets/chart.svg"
import { motion } from "framer-motion";
import { goTo } from "@/utils";

export default function Home() {
  const MotionButton = motion(Button)
  return (
    <>
      <Head>
        <title>Thrive</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack  bgColor={"black.500"} width={"100%"}>
        <Texture/>
        <Header />
        <Stack
          alignItems={"center"}
          width={"100%"}
          direction={"row"}
        >
          <Stack paddingX={20} spacing={6} width="50%">
            <H1>
              Geração de Leads <br /> para times comerciais
            </H1>
            <Paragraph maxWidth={"35rem"}>
              Garantimos que o seu time de vendas receba um caminhão de demanda,
              todos os dias e foque apenas no que realmente importa... vender.
            </Paragraph>
            <MotionButton
          whileHover={{
            x: 10
           
          }}
            _hover={{
              background: 'orange.500'
            }}
            borderRadius={8}
            colorScheme="orange"
            size={"lg"}
            border={'1px solid rgba(255, 255, 255, 0.50)'}
            background={'linear-gradient(92deg, #D94B00 0%, #FF5800 50.52%, #BE4200 100%)'}
            color={"white.500"}
            backgroundColor={'orange.500'}
            fontWeight={'bold'}
            maxWidth={"20rem"}
          >
            RECEBER PROPOSTA EM 5 MIN
          </MotionButton>
          </Stack>
          <Flex
            maxW={"45rem"}
            marginTop={-12}
            alignItems={"center"}
            justifyContent={"center"}
            paddingTop={12}
            width={"60%"}
          >
            <Image alt="illustration" src={ills} />
          </Flex>
        </Stack>
        <Stack marginTop={24} paddingX={20} width={"100%"}>
          <Divider
            borderColor={"white.500"}
            borderWidth={2}
            borderRadius={"full"}
            marginBottom={12}
          />
          <H1>
            O Parceiro de Geração de Demanda <br />
            das marcas mais conhecidas:
          </H1>
          <Stack marginTop={8} spacing={12}>
            <Paragraph fontSize={"xl"}>
              Mais de 15 milhões gerenciados em mídia
            </Paragraph>
            <SimpleGrid
              width={"100%"}
              alignItems={"center"}
              spacing={6}
              columns={4}
            >
              {COMPANIES.map((comp, index) => (
                <Flex justifyContent={"center"} key={index}>
                  <Image
                    width={comp.w}
                    height={comp.h}
                    alt={`company-${index}`}
                    src={comp.img}
                  />
                </Flex>
              ))}
            </SimpleGrid>
          </Stack>
          <Divider
            marginTop={12}
            borderColor={"white.500"}
            borderWidth={2}
            borderRadius={"full"}
          />
        </Stack>
        <Stack
          justifyContent={"space-between"}
          alignItems={"center"}
          paddingX={20}
          direction={"row"}
          width={"100%"}
          marginTop={24}
          id='entrega'
        >
          <Stack spacing={6}>
            <H1 maxWidth={"30rem"}>
              Atraia, Envolva, Conquiste e Retenha. Conheça nosso FUNIL DE
              MARKETING INTELIGENTE
            </H1>
            <Paragraph fontSize={"lg"} maxWidth={"35rem"}>
              Se você deseja transformar visitantes em clientes fiéis, você está
              no lugar certo. No coração de nossa estratégia de sucesso está o
              Funil de Marketing, uma abordagem meticulosamente planejada para
              levar seus clientes em potencial em uma jornada emocionante e
              envolvente.
            </Paragraph>
          </Stack>
          <Flex
            maxW={"35rem"}
            marginTop={-12}
            alignItems={"center"}
            justifyContent={"center"}
            paddingTop={12}
            width={"50%"}
          >
            <Image alt="funil" src={funil} />
          </Flex>
        </Stack>
        <Stack
          justifyContent={"space-between"}
          alignItems={"center"}
          paddingX={20}
          direction={"row-reverse"}
          width={"100%"}
          marginTop={32}
          id='thrive'
        >
          <Stack spacing={6}>
            <Badge
              colorScheme="orange"
              variant={"subtle"}
              width={"fit-content"}
              fontSize={"sm"}
            >
              THRIVE
            </Badge>
            <H1 fontSize={"4xl"} maxW={"45rem"}>
              Somos a peça que falta no seu quebra-cabeça de marketing.
            </H1>
            <Paragraph fontSize={"lg"} maxWidth={"35rem"}>
              Quando você faz parceria com a Thrive, você obtém um esquadrão de
              crescimento personalizado de especialistas comprovados que
              entendem seu negócio e estão comprometidos em alcançar um
              crescimento rápido que aproveite todo o seu potencial. Somos uma
              equipe construída com base na crença de que, quando as pessoas e
              ideias certas se conectam, tudo é possível.
            </Paragraph>
          </Stack>
          <Flex
            maxW={"35rem"}
            alignItems={"center"}
            justifyContent={"center"}
            paddingTop={12}
            width={"50%"}
            position={'relative'}
          >
            <Flex left={-36} position={'absolute'}>
            <Image alt="puzzle" src={puzzle} />
            </Flex>
          </Flex>
        </Stack>
        <Stack
          justifyContent={"space-between"}
          alignItems={"center"}
          paddingX={20}
          direction={"row"}
          width={"100%"}
          marginTop={24}
        >
          <Stack spacing={6}>
            <H1 fontSize={"4xl"} maxW={"40rem"}>
              Sem enrolação. Alto impacto. Nenhum centavo desperdiçado.
            </H1>
            <Paragraph fontSize={"lg"} maxWidth={"35rem"}>
              Estamos hiperfocados em aumentar sua receita. Aproveitamos o
              aprendizado de milhares de experimentos com marcas de sucesso para
              refinar o manual de crescimento que criamos para o seu negócio.
            </Paragraph>
          </Stack>
          <Flex
            maxW={"35rem"}
            alignItems={"center"}
            justifyContent={"center"}
            paddingTop={12}
            width={"50%"}
          >
            <Image alt="chart" src={chart} />
          </Flex>
        </Stack>
        <Stack marginTop={-12} width={"100%"} alignItems={"center"}>
          <MotionButton
          whileHover={{
            scale: 1.05,
           
          }}
            _hover={{
              background: 'orange.500'
            }}
            borderRadius={8}
            colorScheme="orange"
            size={"lg"}
            border={'1px solid rgba(255, 255, 255, 0.50)'}
            background={'linear-gradient(92deg, #D94B00 0%, #FF5800 50.52%, #BE4200 100%)'}
            color={"white.500"}
            backgroundColor={'orange.500'}
            fontWeight={'bold'}
            maxWidth={"30rem"}
          >
            FALE COM UM ESPECIALISTA
          </MotionButton>
        </Stack>
        <Stack
          spacing={12}
          width={"100%"}
          alignItems={"center"}
          justifyContent={"center"}
          marginTop={32}
        >
          <Stack spacing={6}>
            <H1>Início da sua jornada na Thrive</H1>
            <Paragraph maxWidth={"35rem"}>
              A Thrive conta com profissionais que, além da alta qualidade de
              entrega, atuam com um número limitado de contas, oferecendo a
              atenção que você merece
            </Paragraph>
          </Stack>
          <SimpleGrid
            width={"100%"}
            alignItems={"center"}
            justifyContent={"center"}
            boxSize={"fit-content"}
            spacing={6}
            columns={2}
          >
            <Stack
              spacing={6}
              bgColor={"black.300"}
              borderRadius={6}
              paddingX={8}
              paddingY={6}
              width={"fit-content"}
              height={"15rem"}
              justifyContent={"center"}
            >
              <Image alt="onboarding" src={onboarding} />
              <Stack>
                <H1 fontSize={"2xl"}>Onboarding</H1>
                <Paragraph maxW={"25rem"}>
                  Nosso time de especialistas implementa ações que trarão ganhos
                  de curto prazo, enquanto estrutura seu plano de otimização
                  para o longo prazo
                </Paragraph>
              </Stack>
            </Stack>
            <Stack
              spacing={6}
              bgColor={"black.300"}
              borderRadius={6}
              paddingX={8}
              paddingY={6}
              width={"fit-content"}
              height={"15rem"}
              justifyContent={"center"}
            >
              <Image alt="onboarding" src={diagnosis} />
              <Stack>
                <H1 fontSize={"2xl"}>Diagnóstico</H1>
                <Paragraph maxW={"25rem"}>
                  Analisamos o seu caso e apresentamos um projeto feito sob
                  medida para sua operação
                </Paragraph>
              </Stack>
            </Stack>
            <Stack
              spacing={6}
              bgColor={"black.300"}
              borderRadius={6}
              paddingX={8}
              paddingY={6}
              width={"fit-content"}
              height={"15rem"}
              justifyContent={"center"}
            >
              <Image alt="onboarding" src={learning} />
              <Stack>
                <H1 fontSize={"2xl"}>Aprendizado</H1>
                <Paragraph maxW={"25rem"}>
                  Validamos as ações implementadas e estudamos próximos passos
                </Paragraph>
              </Stack>
            </Stack>
            <Stack
              spacing={6}
              bgColor={"black.300"}
              borderRadius={6}
              paddingX={8}
              paddingY={6}
              width={"fit-content"}
              height={"15rem"}
              justifyContent={"center"}
            >
              <Image alt="onboarding" src={growth_cicle} />
              <Stack>
                <H1 fontSize={"2xl"}>Ciclo de crescimento</H1>
                <Paragraph maxW={"25rem"}>
                  Otimização e escala contínua dos resultados de sua operação de
                  mídia feita pelos especialistas da Thrive.
                </Paragraph>
              </Stack>
            </Stack>
          </SimpleGrid>
        </Stack>
        <Stack
          align={"center"}
          justifyContent={"space-between"}
          direction={"row"}
          paddingX={20}
          width={"100%"}
          marginTop={32 }
        >
          <Stack spacing={6} width={"50%"}>
            <H1 fontWeight={"normal"} fontSize={"2xl"} maxW={"30rem"}>
              As parcerias e conhecimentos que impulsionam o seu crescimento
            </H1>
            <Paragraph maxW={"30rem"}>
              Somos parceiros das melhores plataformas, garantindo a eficiència
              do seu investimento que levarão a sua empresa para o próximo
              nível.
            </Paragraph>
          </Stack>
          <Flex width={"10%"} align={"center"} justifyContent={"center"}>
            <Box
              height={"12rem"}
              width={0.5}
              backgroundImage={
                "linear-gradient(0deg, #F7931E 0%, rgba(247, 147, 30, 0.00) 0%, #F7931E 52.08%, rgba(247, 147, 30, 0.00) 100%);"
              }
            />
          </Flex>
          <SimpleGrid
            width={"50%"}
            alignItems={"center"}
            spacing={8}
            columns={3}
          >
            {PARTNERS.map((comp, index) => (
              <Flex justifyContent={"center"} key={index}>
                <Image
                  width={comp.w}
                  height={comp.h}
                  alt={`company-${index}`}
                  src={comp.img}
                />
              </Flex>
            ))}
          </SimpleGrid>
        </Stack>
        <Stack marginTop={32} paddingX={20} spacing={12} alignItems={"center"} width={"100%"}>
          <Badge
            fontSize={"2xl"}
            paddingX={4}
            borderRadius={4}
            colorScheme="orange"
            variant={`subtle`}
            width={"fit-content"}
          >
            ESTÚDIOS THRIVE
          </Badge>
          <Stack direction={"row"}>
            <Image width={300} alt="ex" src={ex} />
            <Stack>
              <Image width={430} alt="ex-dois" src={exDois} />
              <Image width={430} alt="ex-dois" src={exDois} />
            </Stack>
            <Image width={300} alt="ex" src={ex} />
          </Stack>
        </Stack>
        <Stack marginTop={24} width={"100%"} alignItems={"center"}>
        <MotionButton
          whileHover={{
            scale: 1.05,
           
          }}
            _hover={{
              background: 'orange.500'
            }}
            borderRadius={8}
            colorScheme="orange"
            size={"lg"}
            border={'1px solid rgba(255, 255, 255, 0.50)'}
            background={'linear-gradient(92deg, #D94B00 0%, #FF5800 50.52%, #BE4200 100%)'}
            color={"white.500"}
            backgroundColor={'orange.500'}
            fontWeight={'bold'}
            maxWidth={"30rem"}
          >
            FALE COM UM ESPECIALISTA
          </MotionButton>
        </Stack>
        <Stack
          alignItems={"end"}
          direction={"row"}
          justifyContent={"space-between"}
          paddingX={20}
          marginTop={32}
        >
          <Stack spacing={6}>
            <HStack spacing={4}>
              <Image width={60} alt="logo" src={logo} />
              <Paragraph fontSize={"sm"} maxW={"25rem"}>
                Estamos sediados em Curitiba, com filial em Porto Alegre, mas
                você também pode encontrar nossa equipe em São Paulo, Rio de
                Janeiro e Fortaleza.
              </Paragraph>
            </HStack>
            <Stack>
              <Paragraph fontWeight={"bold"}>Nossos escritórios</Paragraph>
              <Paragraph fontSize={"xs"}>
                Curitiba (Matriz): R. Conselheiro Laurindo, 809 - Centro,
                Curitiba - PR.
              </Paragraph>
              <Paragraph fontSize={"xs"}>
                Porto Alegre: Av. Dolorez Alcaraz Caldas, 90 - 8º. Andar, Porto
                Alegre, Rio Grande do Sul
              </Paragraph>
              <Paragraph fontSize={"xs"}>
                Contato: contato@grupothrive.com
              </Paragraph>
            </Stack>
          </Stack>
          <Stack
            _hover={{ filter: "grayscale(0)" }}
            filter={"grayscale(1)"}
            alignItems={"end"}
          >
            <SimpleGrid columns={4} spacing={2} boxSize={"fit-content"}>
              <IconButton
                size={"lg"}
                variant={"ghost"}
                aria-label="instagram"
                icon={<FaInstagram />}
                onClick={()=> goTo('https://www.instagram.com/grupo.thrive/')}
              />
              <IconButton
                size={"lg"}
                variant={"ghost"}
                aria-label="linkedin"
                icon={<FaLinkedinIn />}
                onClick={()=> goTo('https://www.linkedin.com/company/thrivebr/mycompany/')}
              />
              <IconButton
                size={"lg"}
                variant={"ghost"}
                aria-label="yt"
                icon={<FaYoutube />}
                onClick={()=> goTo('https://www.youtube.com/@GrupoThrive')}


              />
              <IconButton
                size={"lg"}
                variant={"ghost"}
                aria-label="spotify"
                icon={<FaSpotify />}
                onClick={()=> goTo('https://www.linkedin.com/company/thrivebr/')}

              />
            </SimpleGrid>
            <HStack>
              <Flex borderRadius={6} overflow={"hidden"}>
                <Image height={50} alt="googlePartner" src={googlePartner} />
              </Flex>
              <Flex borderRadius={6} overflow={"hidden"}>
                <Image height={50} alt="metaCertified" src={metaCertified} />
              </Flex>
              <Flex borderRadius={6} overflow={"hidden"}>
                <Image height={50} alt="metaBusiness" src={metaBusiness} />
              </Flex>
            </HStack>
          </Stack>
        </Stack>
        <Stack
          spacing={6}
          paddingBottom={12}
          paddingX={20}
          alignItems={"center"}
        >
          <Divider w={"100%"} borderWidth={0.5} borderColor={"white.500"} />
          <Paragraph fontSize={"x-small"}>
            Desenvolvido por Pedro Copatti | © Thrive 2023 | Política de
            privacidade
          </Paragraph>
        </Stack>
      </Stack>
    </>
  );
}
